### ISSUE TITLE
equalsHashCode use instanceOf

### ISSUE THREAD

**Issue by kevinduffey** [mulesoft-labs/raml-java-tools#11]
The generated equals code uses the approach of getClass comparison. According to Josh Bloch and elsewhere, the better approach is to use instanceOf:

https://www.artima.com/intv/bloch17.html

It also allows the remove of the null check at the start of the equals method:

The generated code should be something like:

@Override
public boolean equals(Object o){
        if (this == o) return true;
        if (!(o instanceof Other)) return false;
        // call super.equals to account for any parent class equals impl
        if (!super.equals(o)) return false;
        Other other = (Other) o;
        return Objects.equals(getSomething(), other.getSomething());
}

**Comment by jpbelang** [comment]
This is semantically not the same.  

Furthermore, unless specifically necessary, it can break the equals() contract (as mentioned in that post).

I've written another plugin. core.equalsAndHashCodeWithSubclasses
