### ISSUE TITLE
Generated java of subtypes won't compile

### ISSUE THREAD

**Issue by vromero** [mulesoft-labs/raml-java-tools#30]
When using a RAML that has for instance a response envelope:

`myEnvelope` that has some members in it, when creating a subtype, eg: EnvelopeForParticularResource it will generate enums and other types again, creating a change in the Java signature and therefore not compiling for the subtype.

See the following example project to reproduce [raml-defined-example.tar.gz](https://github.com/mulesoft-labs/raml-java-tools/files/3204478/raml-defined-example.tar.gz)

As a dirty workaround I've been able to change the `type: mylib.myType` for an `type: !include ...` which does the trick but is a far cry from ideal.

**Comment by jpbelang** [comment]
Being discussed here:
https://github.com/mulesoft-labs/raml-for-jax-rs/issues/402
