### ISSUE TITLE
Generate equals and hashCode methods

### ISSUE THREAD

**Issue by kevinduffey** [mulesoft-labs/raml-java-tools#8]
I dont know if this is in place yet.. but because this tool generates the pojo methods, it would be beneficial that it could also generate modern day equals() and hashCode() methods (making use of Objects.equals() and Objects.hash()).

**Comment by jpbelang** [comment]
There is a plugin available for this called equalsAndHashcode:
https://github.com/mulesoft-labs/raml-java-tools/blob/master/raml-to-pojo/src/main/resources/META-INF/ramltopojo-plugin.properties

The code is here.  You can specify fileds that you want to be considered in the methods.

https://github.com/mulesoft-labs/raml-java-tools/blob/master/raml-to-pojo/src/main/java/org/raml/ramltopojo/extensions/tools/AddEqualsAndHashCode.java

**Comment by kevinduffey** [comment]
I saw this after.. thank you. It would be great to have a few more detailed examples showing how to use all these additional addons with bundled raml api, types, etc.

**Comment by kevinduffey** [comment]
I know.. it is a work in progress! I wish I could devote more time to offer commits for you. I also had a plan to build a kick butt tool around RAML and generators.. but things have changed in the past couple years.. with AMF.. I am not even sure the right way to do something like that now.
